IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLogMeta' AND COLUMN_NAME = 'IsJson')
    BEGIN
      ALTER TABLE AuditLogMeta
        ADD IsJson bit NOT NULL DEFAULT(0)
    END
GO